# Generated by Django 5.0.6 on 2024-06-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='Typ',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
