# Generated by Django 5.0.6 on 2024-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://metropizza.com.au/wp-content/uploads/2023/06/food-placeholder.jpeg', max_length=500),
        ),
    ]
